# Numpy
Numpy is an all-purpose numerical computational library in Python. Its basic element and strong feature is the _array_. It is implemented in C and Fortran for maximum speed and wrapped in Python using Cython.  
Numpy strength is all about _vectorialization_. If you can rewrite a problem so that it can be solved as a vector problem (instead of looping, for example), you will see enormous improvement in computational speed.  
Example below (the performance depends on the machine, but you should see a large improvement in time)

In [1]:
%%timeit
# Sum all the numbers from 1 to 1e6
# First the old way
tot = 0
for i in range(1,1000001):
    tot += i

36.2 ms ± 715 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [2]:
%%timeit
import numpy as np
# Sum all the numbers from 1 to 1e6
# Now using Numpy
tot = np.sum(np.arange(1,1000001,dtype='long'))

1.9 ms ± 43.6 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


There are a few differences between arrays and Python lists and tuples:
+ Arrays occupy contiguous block in memory (like in C)
+ Arrays elements must all be of the same type (no int/float/string mixing). The element type can be specified with the keyword _`dtype`_ at array creation, and if possible automatic casting will be performed.
+ Arrays dimensions must be consistent (they are less flexible than lists). Think of them as N-dimensional vectors (or matrices)

## Creating an Array
There are a few way to create arrays in numpy. The most useful one is the function `array()`, which converts the standard Python data types (lists, tuples) in numpy arrays. Note that all the elements of the original variable must be of the same type (casting will be attempted).

In [8]:
# Examples
import numpy as np
a = np.array([1,2,3,4,5]) # 1D vector
b = np.array([[1,2],[3,4]]) # 2D vector
c = np.array([5,4,3],dtype='float') # with casting
d = np.array([1,3,6],dtype='complex') # also with imaginary numbers

for arr in [a,b,c,d]:
    print(arr)

[1 2 3 4 5]
[[1 2]
 [3 4]]
[5. 4. 3.]
[1.+0.j 3.+0.j 6.+0.j]


Anoter way to create arrays, is to use numpy generator functions (similar to Matlab):
+ `arange([start,]stop[,step,dtype])`: create a range of values. Stop value is not usually included.
+ `linspace(start,stop,num)`: create a linear interval sampled in N points (extremities included)
+ `logspace(start,stop,num,base)`: same as linspace, but in logarithmic scale (default is base 10)
+ `random.rand(nrows,ncols)`: random numbers in the range [0,1] (uniform distribution)
+ `random.randn(nrows,ncols)`: random numbers (standard normal distribution)
+ `diag([list])`: digonal matrix
+ `zeros(nrows,ncols)`: zeros matrix
+ `ones(nrows,ncols)`: ones matrix
+ `eye(nrows,ncols)`: zeros matrix with ones on the diagonal

## File I/O
You can read data from files normally with Pyhton I/O functions, but Numpy has some useful alternatives. If you have a formatted text file (.txt, .csv, .dat, etc...) you can use `genfromtxt()` to read it into a numpy array. To save an array to a text file, you use `savetxt()`
```
data = genfromtxt('input_data.csv') # to read data
savetxt('output.dat',data,[format]) # to save data on file
```
Numpy also has its own binary file format `.npy` to store arrays (similar to Matlab `.mat`)
```
data = random.rand(10,5)
save('random_data.npy') # save to file
new_data = load('random_data.npy') # load file
```
with `save` you can only store one array per file. If you need to save multiple arrays, you can use `savez`, which will save them in an uncompressed .npz file. It is basically a zip file containing multiple .npy files [(more info)](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html)